In [2]:
### 복습
# Numpy (Numerical Python)
# Numpy => Vector와 Matrix연산에 강점.
# ndarray => n-차원의 배열
# list와 거의 유사. but ndarray의 각 요소는 모두 같은 데이터타입이어야 한다.
# ndarray를 생성하려면 어떻게 해야 하나??
# => numpy.array([1,2,3,4])   - list를 이용해 array라는 클래스 타입의 객체를 생성
# => numpy.arange()
# => random기반의 생성함수 : zeros, ones, empty, full
# => shape, reshape() => view가 만들어짐! (원본변화x) 
# => resize() => 새로운 numpy가 만들어짐

In [11]:
### 오늘
# indexing, slicing
# 기본 indexing, boolean indexing, fancy indexing

## 기본 indexing
import numpy as np

arr = np.arange(10,20,1)
print(arr)

# enumerate는 반복문 사용시 index값을 추출하기 위해서 사용!
for idx,temp in enumerate(arr):         #index값을 같이 가져온다
    print('인덱스 : {}, 값은 : {}'.format(idx,temp))



[10 11 12 13 14 15 16 17 18 19]
인덱스 : 0, 값은 : 10
인덱스 : 1, 값은 : 11
인덱스 : 2, 값은 : 12
인덱스 : 3, 값은 : 13
인덱스 : 4, 값은 : 14
인덱스 : 5, 값은 : 15
인덱스 : 6, 값은 : 16
인덱스 : 7, 값은 : 17
인덱스 : 8, 값은 : 18
인덱스 : 9, 값은 : 19


In [17]:
## ndarray의 slicing도 python의 list와 동일한 형태로 사용가능.

arr = np.arange(0,5,1)
print(arr)
print(arr[0:2])
print(arr[0:-1])     # 맨 마지막 요소만 제외하고 슬라이싱
print(arr[1:4:2])    # 

# 2차원 형태의 ndarray를 slicing
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
print(arr)
print(arr[1,1])   # 6, 일반적인 2차원의 indexing
print(arr[1,:])   # [5 6 7 8]
print(arr[1:3,:]) # [[5  6  7  8]
                  #  [9 10 11 12]]
print(arr[0])     # [1 2 3 4]

[0 1 2 3 4]
[0 1]
[0 1 2 3]
[1 3]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6
[5 6 7 8]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [144]:
## boolean indexing

np.random.seed(1)   # 항상 똑같은 난수
arr = np.random.randint(1,20,(10,))
print(arr)

# boolean mask
# [6 12 13 9 10 12 6 16 1 17]
# [True, True, False, False, ... , False] : boolean mask
# 결국 우리가 구한 boolean mask => arr % 2 == 0
print(arr % 2 == 0)
print(arr[arr % 2 == 0])   # boolean indexing

for temp in arr:
    if temp % 2 == 0 :
        print(temp, end =' ')
print()        
# 위의 작업을 boolean indexing을 사용해 쉽게 해보자.
# boolean mask라는 것이 있다.
# 원본 ndarray와 shape이 같고 그 요소값이 모두 boolean(True,False)
# 로 구성된 ndarray
# 이 boolean mask를 이용해서 indexing하는 방식을 boolean indexing

np.random.seed(1)  
arr = np.random.randint(1,20,(10,))
print(arr)



[ 6 12 13  9 10 12  6 16  1 17]
6 12 10 12 6 16 
[ 6 12 13  9 10 12  6 16  1 17]
[ True  True False False  True  True  True  True False False]
[ 6 12 10 12  6 16]


In [44]:
## Fancy indexing
# ndarray에 index배열(list형식)을 전달하여 배열요소를 참조하는 방식
arr = np.array([1,2,3,4,5])         
print(arr)                
print(arr[[1,3,4]])       # 내가 원하는 위치만 지정해서 뽑아온다

# Fancy indexing에 대해서 좀 더 알아보자
import numpy as np

arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)

print(arr[2,2])           # 10, indexing
print(arr[1:2,2])         #  [[4 5 6 7]] => [6]
print(arr[1:2,1:2])       #  [[5]]

print(arr[[0,2],2])       #   [2 10]
print(arr[[0,2],2:3])     #  [[2]
                          #   10]]
print(arr[[0,2],[0,2]])   # [0,10]??  - 다차원에서 내부적 구현 상 두개 다 fancy indexing이 되지 않는다.
# 이런경우를 위해 numpy가 함수를 하나 제공.
# np.ix_()
print(arr[np.ix_([0,2],[0,2])])

# indexing은 차원이 줄어들고, slicing은 차원이 줄어들지 않는다.

[1 2 3 4 5]
[2 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
[6]
[[5]]
[ 2 10]
[[ 2]
 [10]]
[ 0 10]
[[ 0  2]
 [ 8 10]]


In [54]:
### ndarray에 대한 연산
import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6]])    # 2 x 3 ndarray
arr2 = np.arange(10,16,1).reshape(2,3).copy() # 2 x 3 ndarry
arr3 = np.arange(10,16,1).reshape(3,2).copy() # 3 X 2 ndarry

# ndarray 연산의 기본은 같은 위치에 있는 원소간의 연산을 수행
# shape이 다르면 연산이 수행되지 않는다!
print(arr1 + arr2)   # 4칙연산 모두 같다!
# 행렬쪽에서 우리가 많이 사용하고 조심해야 하는 연산
# => 행렬곱연산.
# 행렬곱 연산이 일어나려면 두 개의 행렬이 어떠한 형태를 가져야 하나?
# 앞쪽 행렬의 열과 뒤쪽 행렬의 행의 수가 일치해야한다!
print(np.matmul(arr1,arr3))
# 행렬곱은 2차원 matrix에 대해서만 가능하다.

[[11 13 15]
 [17 19 21]]
[[ 76  82]
 [184 199]]


In [62]:
# 그러면 정말 같은 shape을 가지는 ndarray끼리만 4칙연산이 가능한가?
# 다른 shape을 가지는 ndarry를 이용해서 4칙연산이 가능하도록
# broadcasting을 지원
import numpy as np

arr1 = np.array([[1,2,3],
                [4,5,6]])    # (2,3) ndarray
arr2 = np.array([7,8,9])     # (3,) ndarray
print(arr1)
print(arr2)
print(arr1 + arr2) # >>> 에러?  No!  Why?  => broadcasting
print(arr1 + 10)   # >> broadcasting

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]
[[11 12 13]
 [14 15 16]]


In [66]:
### 전치행렬 & iterator 

# numpy ndarray는 차원의 개념이 있어요!
# 0차원 => 하나의 숫자 => scalar (ex. 5)
# 1차원 => 열로 구성 => vector (ex. [1 3 5 7 9])
# 2차원 => 행과 열로 구성 => matrix (ex. [[1 2 3]
#                                         [4 5 6]])
# 3차원 이상 => array라는 표현을 쓴다.

# 전치행렬
# => 원본행렬의 행은 열로, 열은 행으로 바꾼 matrix를 의미
# 이렇게 만든 전치행렬(transpose)은 view다!
# 수학적으로 전치행렬을 표현할때는 위첨자로 T를 이용한다.

import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print(arr.T)   # 전치행렬을 구할때 T 속성을 이용

# 1차원 vector에 대해서 전치행렬을 구하면 어떻게 되나?
# 1차원 vector에 대해서는 전치행렬을 구할 수 없다.

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [83]:
### iterator(반복자)
# 반복문은 일반적으로 for문과 while을 사용하는데
# 반복하는 횟수를 알고 있을때는 for
# 조건에 따라서 반복할때는 while

# numpy array를 반복출력할 때는 일반적으로 for!

import numpy as np

## 1차원 numpy array(ndarray)에 대한 요소를 출력!
arr = np.array([1,2,3,4,5])

# for문을 이용한 반복처리
for tmp in arr:
    print(tmp, end=' ')
print()

# while문과 iterator를 이용해서 반복처리     iterator : 지시자, 가리키는 놈
arr = np.array([1,2,3,4,5])
it = np.nditer(arr, flags=['c_index'])
while not it.finished:
    idx = it.index     # 0
    print(arr[idx], end = ' ')
    it.iternext()      # 화살표 옮기는 작업
print()    
    
## 2차원 matrix에 대해서 각 요소를 출력하고 싶다.

# for문
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

for tmp1 in range(arr.shape[0]):    # arr.shape => (2,3)
    for tmp2 in range(arr.shape[1]):
        print(arr[tmp1,tmp2], end= ' ')
print()

# iterator를 이용한 반복처리
it = np.nditer(arr, flags=['multi_index'])

while not it.finished:
    idx = it.multi_index   # (0,0)
    print(arr[idx], end = ' ')
    it.iternext()

1 2 3 4 5 
1 2 3 4 5 
[[1 2 3]
 [4 5 6]]
1 2 3 4 5 6 
1 2 3 4 5 6 

In [95]:
# numpy ndarray의 비교연산
# 비교연산도 사칙연산과 유사하게 동작
import numpy as np

np.random.seed(4)
arr1 = np.random.randint(0,10,(2,3))
arr2 = np.random.randint(0,10,(2,3))

print(arr1)
print(arr2)
print(arr1 == arr2)   # boolean mask
print(arr1 > arr2)    # boolean mask

arr1 = np.arange(10)
arr2 = np.arange(10)
print(np.array_equal(arr1,arr2))

[[7 5 1]
 [8 7 8]]
[[2 9 7]
 [7 7 9]]
[[False False False]
 [False  True False]]
[[ True False False]
 [ True False False]]
True


In [105]:
# 집계함수, 수학함수와 axis(축)
# 집계함수 : 합, 평균, 표준편차, 분산
# 수학함수 : 최대, 최소, 제곱근, 제곱값, 로그값

import numpy as np

arr = np.arange(1,7,1).reshape(2,3).copy()
print(arr)

print(np.sum(arr))     # 21   합계
print(arr.sum())       # 21
print(np.mean(arr))    # 3.5  평균
print(np.max(arr))     # 6    최대
print(np.min(arr))     # 1    최소
print(np.argmax(arr))  # 5   최댓값의 index를 리턴
print(np.argmin(arr))  # 0   최솟값의 index를 리턴
print(np.std(arr))     # 표준편차, 1.707825127659933
print(np.sqrt(arr))    # 제곱근



[[1 2 3]
 [4 5 6]]
21
21
3.5
6
1
5
0
1.707825127659933
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [131]:
# axis 개념을 잘 이해해야 한다!
# Numpy의 모든 집계함수는 기본적으로 axis를 기준으로 계산
# 만약 axis를 지정하지 않으면 axis는 None으로 설정
# 대상범위가 배열의 전체로 지정

##1차원
arr = np.array([1,2,3,4,5])    # 1차원의 ndarray
# axis는 축을 의미하고 이 축은 결국 숫자로 표현(0,1,2,3,4,5,...)
# 1차원에서 axis값은 0밖에 쓸 수 없다.
print(arr.sum(axis=0))   # 15
# 1차원은 axis가 큰 의미가 없다!

##2차원


np.random.seed(1)
arr = np.random.randint(0,12,(4,3))
print(arr)
print(arr.shape)    # (4, 3)
print(arr.sum())    # 축이 명시가 안됐다. sum()의 대상은 전체 ndarray가 된다.
print(arr.sum(axis=0)) 
print(arr.sum(axis=1))
print(arr.argmax(axis=1))
# 축을 명시해 본다.
# 2차원이기 때문에 axis는 0과 1을 사용할 수 있다.
# 0 => 행방향, 1 => 열방향

##3차원 
#3차원이면 axis는 0,1,2 3개 사용할 수 있다.
# 0 => 면, 1=> 행방향, 2 => 열방향

np.random.seed(1)
arr = np.random.randint(0,12,(2,2,3))
print(arr)
print(arr.sum(axis=0))

## 굳이 집계함수를 이용해서 계산을 하지 않아도 된다!
## 로직을 이용해서 처리해도 괜찮다!
## 하지만 속도차이가 비교할 수 없을정도로 집계함수가 빠르다!

15
[[ 5 11  8]
 [ 9 11  5]
 [ 0  0  1]
 [ 7  6  9]]
(4, 3)
72
[21 28 23]
[24 25  1 22]
[1 1 2 2]
[[[ 5 11  8]
  [ 9 11  5]]

 [[ 0  0  1]
  [ 7  6  9]]]
[[ 5 11  9]
 [16 17 14]]


In [151]:
## 연습문제

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
# ndarray arr 안에 10보다 큰 수가 몇개있는지 알아보려면 어떻게 해야 하는가?

print(len(arr[arr>10]))   # 내 풀이

print((arr > 10).sum())  # 강사님 풀이
                         # 파이썬은 false는 0으로 간주하고, true는 1로 간주
                         # 따라서 .sum() 함수를 사용할 수 있다.

6
6


In [169]:
## 정렬은 상당히 많이 사용하는 기능이다!

# np.sort() : 인자로 들어가는 원본 ndarray는 변화가 없고
#             정렬된 복사본이 만들어져서 리턴된다!

# arr.sort() : 원본 배열을 정렬하고 리턴이 없다!

import numpy as np

arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

print(np.sort(arr))   # [0 1 2 3 4 5 6 7 8 9]  - 정렬된 복사본이 리턴
print(arr)            # 원본은 정리 안된 그대로

print(arr.sort())     # 리턴이 없기 때문에 None이 리턴됨
print(arr)            # 원본을 찍어보면 원본이 정렬돼서 리턴됨

# 특수한 슬라이싱을 이용하면 역순으로 정렬할 수 있다!
# sort는 기본적으로 오름차순 - 내림차순으로 정리하고 싶을 때
print(np.sort(arr)[::-1])

[0 1 2 3 4 5 6 7 8 9]
[8 4 7 3 5 9 1 0 6 2]
[0 1 2 3 4 5 6 7 8 9]
[8 4 7 3 5 9 1 0 6 2]
None
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [173]:
### numpy array를 연결하려면 어떻게 해야 하나요?

import numpy as np

## 행방향 붙이기
arr = np.array([[1,2,3],
                [4,5,6]])    # (2,3)
new_row = np.array([7,8,9])  # (3,)

result = np.concatenate((arr,new_row.reshape(1,3)),axis=0)
print(result)
# np.concatenate((붙일 곳, 붙일 것),axis=방향) / 차원을 갖게 해줘야 한다.

## 열방향 붙이기
new_col = np.array([7,8,9,10])

result = np.concatenate((arr,new_col.reshape(2,2)),axis=1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [181]:
### Numpy의 delete()
# delete()도 axis를 기준으로 삭제가 진행

# 만약 axis를 명시하지 않으면 자동으로 1차배열로 변환이 된 후 삭제
arr = np.array([[1,2,3],
                [4,5,6]])    
result = np.delete(arr,1)    # 1차배열로 변환한 후 삭제
                             # [1 2 3 4 5 6]
                             # 1번 index 삭제
print(result)                # [1 3 4 5 6]

# axis를 명시하고 삭제

result = np.delete(arr,1,axis=1)

print(result)     # [[1 3]
                  #  [4 6]]

# axis=-1 은 항상 마지막 axis : 열을 지칭함
result = np.delete(arr,1,axis=-1)
print(result)

[1 3 4 5 6]
[[1 3]
 [4 6]]
[[1 3]
 [4 6]]
